@startuml
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName Arial
skinparam DefaultFontSize 12

title Ciclo de Vida del Dato (Tamizaje a Diagnóstico Social)

start

:Paciente;
:Questionnaire (Cuestionario);
:QuestionnaireResponse;
:StructureMap (FML);
:Bundle Collection (Observations);
:Validación del flujo (opcional);
:Bundle Transaction;
:FHIR Server;
:Base de datos;
:Búsquedas FHIR;
:Condition (creado posteriormente por regla clínica);

end
@enduml
