@startuml
left to right direction
skinparam monochrome true
skinparam shadowing false
skinparam actorStyle awesome
skinparam defaultFontName Arial
skinparam DefaultFontSize 12

actor Paciente as P
actor "Trabajador(a) Social" as TS
actor "Profesional APS" as PA

rectangle "CESFAM Las Cabras\nSeguimiento Preventivo" {
  usecase "Responder cuestionario\nde tamizaje" as UC1
  usecase "Registrar diagnóstico\nsocial" as UC2
  usecase "Visualizar alerta y\ncontextualizar inasistencias" as UC3
}

P --> UC1
TS --> UC2
PA --> UC3
@enduml