@startuml
skinparam monochrome true
skinparam shadowing false
skinparam actorStyle awesome
skinparam defaultFontName Arial
skinparam DefaultFontSize 12
left to right direction

actor "Paciente Hipertenso" as Paciente
actor "Trabajador(a) Social" as TS
actor "Enfermero(a) Cardiovascular" as Enfermero

rectangle "CESFAM Las Cabras\nPrograma Salud Cardiovascular" {
    usecase "Responder cuestionario de tamizaje" as UC1
    usecase "Registrar diagnóstico social\n(Validar Condition con evidencia)" as UC2
    usecase "Visualizar alerta y coordinar\nalternativas asistenciales" as UC3
}

Paciente --> UC1
TS --> UC2
Enfermero --> UC3
@enduml
