@startuml
left to right direction
skinparam packageStyle rectangle
skinparam actorStyle awesome
skinparam monochrome true

actor "Paciente" as pac
actor "Trabajador(a) Social" as ts
actor "Enfermero(a) de Cabecera" as enf

package "CESFAM Las Cabras - Control Cardiovascular" {
  usecase "Responder Cuestionario de Tamizaje\n(QuestionnaireResponse)" as UC1
  usecase "Registrar Diagnóstico Social\n(Condition)" as UC2
  usecase "Visualizar Alerta de\nInseguridad de Transporte" as UC3
  usecase "Coordinar Alternativas\nAsistenciales" as UC4
}

pac --> UC1
ts --> UC2
enf --> UC3
enf --> UC4

UC2 .> UC1 : <<usa evidencia>>
UC4 .> UC3 : <<requiere>>

@enduml
